import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import chatRoutes from './src/routes/routes.js';
import connectDB from "./src/config/db.js";
dotenv.config();
const app = express();
connectDB();
app.use(cors());
app.use(express.json());
app.use('/api/chat', chatRoutes);
app.get('/', (req, res) => res.send('Cyber AI Assistant Backend is Running!'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port:${PORT}`));